### ISSUE TITLE
Adding libGrowingIORNPlugin.a can not use location. [iOS]

### ISSUE THREAD

**Issue by FaiChou** [growingio/react-native-growingio#4]
After I adding `react-native-growingio` to my project, `location` just broke up.

![exception](https://user-images.githubusercontent.com/18500846/42206988-56146370-7edb-11e8-82d1-b53caaa653ef.jpeg)

After tried remove `.a`, `location` works well !!

`Location` is a big part of my project's feature, after launch app to home page, it will get current position. It is very well before adding `libGrowingIORNPlugin.a `. But .

PS. I added `LocationAlwaysUse`, `LocationAlwaysUseAndWhileUse`, `LocationUsage`, `LocationWhenInUse` these four descriptions to info.plist.

My environment:

```bash
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 9.5.0
  Yarn: 1.5.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

**Comment by FaiChou** [comment]
@NanNanCHN  

这是个临时解决的方法. 试了下可以的.

每次执行yarn 都需要手动更改吧?
而且多人协作的项目也得让其他参与的同事都改吧?

react-native-growingio 啥时候能优化掉这个bug?

**Comment by NanNanCHN** [comment]
@FaiChou 
这确实是临时解决方式,而且存在一定工程风险.
本质上来讲,这是facebook的bug,不属于growingio的问题,暂时不清楚facebook何时以及是否会改.
你提到的多人协作项目的问题,这里可以给你个参考,用method swizzing 去让RCTEventEmitter 的initialize方法不执行原实现即可;
或者
可以尝试解决方式2 看是否奏效:
在main.m中添加
```
[Growing setAspectMode:GrowingAspectModeDynamicSwizzling];
```
使用第二种hook模式

**Comment by FaiChou** [comment]
好的谢谢. 

使用第二种不行.

尝试第一种method swizzle也未果, 还是用手动注释方法吧.

我的尝试方法:

```
#import "RCTEventEmitter+RNSwizzle.h"
#import <objc/runtime.h>

@implementation RCTEventEmitter (RNSwizzle)
+ (void)load {
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    Class class = [self class];
    
    SEL originalSelector = @selector(initialize);
    SEL swizzledSelector = @selector(swizzledInitialize);
    
    Method originalMethod = class_getInstanceMethod(class, originalSelector);
    Method swizzledMethod = class_getInstanceMethod(class, swizzledSelector);
    
    method_exchangeImplementations(originalMethod, swizzledMethod);
  });
}
+ (void)swizzledInitialize {
  if (self == [RCTEventEmitter self]) {
    // just doing nothing!
  }
}

@end
```

**Comment by NanNanCHN** [comment]
@FaiChou 方便的话可否给我一个可以复现的demo

**Comment by FaiChou** [comment]
rn demo splash页结束后跳到home页, home页在willmount进行请求地理位置, 立马报错. (添加了growingio.a 后)

```
  public componentDidMount() {
    this.fetchLocation();
  }

  private fetchLocation = () => {
    getLongitudeAndLatitude().then(({longitude, latitude}) => {
      getLocation(longitude, latitude).then((po) => {
        this.props.dispatch({
          type: 'address/changeAddress',
          payload: po,
        });
        CurrentCity.cityname = po.city;
        CurrentCity.citycode = po.citycode;
      });
    }).catch(ex => {
      Log('定位失败', ex);
    });
  }
```

**Comment by NanNanCHN** [comment]
@FaiChou 可以提供一个直接复现的demo工程么?

**Comment by NanNanCHN** [comment]
[rn-patch.zip](https://github.com/growingio/react-native-growingio/files/2166299/rn-patch.zip)

@FaiChou 你可以在工程中引入这个patch fix这个问题,日后如果facebook 修掉了,可以把patch删除

**Comment by FaiChou** [comment]
OK. 可以使用 👍🏻
