### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by FaiChou** [growingio/react-native-growingio#5]
当我将项目使用Pod来管理就报了这个错.

其他的第三方库一般都会有一个`.podspec` 比如`react-native-video.podspec`, 所以可以迁移到podfile里:

```
pod 'react-native-video', :path => '../node_modules/react-native-video'
```

可是`growingio`没提供`.podspec`, 就无法迁移到pod.

在编译时候就报了错:

```
'React/RCTBridgeModule.h' file not found
```

同样的`RCTWeChat`也遇到相同问题, 经过在RCTWeChat.xcodeproj里的`header search  path`添加`$(SRCROOT)/../../react-native/React`recursive, 这样就可以解决相同的问题.

但是growingio用相同方式不能解决.

![image](https://user-images.githubusercontent.com/18500846/42266447-001f3ea8-7fa9-11e8-986a-fbc5e3c9e4ea.png)

```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 9.5.0
  Yarn: 1.5.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

**Comment by NanNanCHN** [comment]
@FaiChou 后续版本已经支持了pods,待推出;目前还是建议你按文档集成;

**Comment by FaiChou** [comment]
已经成功将pod里的rn sdk挪回Libraries下

**Comment by NanNanCHN** [comment]
好的 先关闭了 有问题再reopen

**Comment by FaiChou** [comment]
关于使用Pods管理报 `'React/RCTBridgeModule.h' file not found` 的解决方案:

https://github.com/facebook/react-native/issues/20762

**Comment by HideOnBushTuT** [comment]
@FaiChou 你好！请问你是怎么解决这个问题的？我尝试了Facebook issue 里的方法无效！
