### ISSUE TITLE
是否兼容rn最新版本？

### ISSUE THREAD

**Issue by tabfed** [growingio/react-native-growingio#6]
我看官网说是修改rn、react-navigation源码，是否兼容最新版本？

**Comment by tabfed** [comment]
我现在是0.57.4，没有办法兼容吗？

**Comment by ldkxingzhe** [comment]
@tabfed 目前确认兼容的版本是 0.46 - 0.56， 我们测试下0.57版本是否兼容。 另外此仓库为IOS专用的， 如果是React Native 修改相关的issues, 可以在https://github.com/growingio/GIORNHook 这个仓库提issues

**Comment by ldkxingzhe** [comment]
测试通过， 兼容React Native 0.57 @tabfed

**Comment by tabfed** [comment]
@ldkxingzhe 感谢，已经在生产环境上用上了
