### ISSUE TITLE
接入无埋点的SDK后报以下错误

### ISSUE THREAD

**Issue by zhujianguo** [growingio/react-native-growingio#7]
![6b82a9aabdfc44a80124a7fa16677b7d](https://user-images.githubusercontent.com/17714962/52895795-31498e80-31fa-11e9-960b-9e9f4155431b.jpg)

**Comment by sishen** [comment]
@zhujianguo 能了解一下你是怎么集成的吗，用的是什么版本，包括 RN、Android SDK、RN SDK，谢谢。

**Comment by zhujianguo** [comment]
> @zhujianguo 能了解一下你是怎么集成的吗，用的是什么版本，包括 RN、Android SDK、RN SDK，谢谢。

我按着官网的步骤集成，但是在集成无埋点SDK之前我集成过埋点SDK，但是相关的我有做删除
各版本如下：
![image](https://user-images.githubusercontent.com/17714962/52895909-a6699380-31fb-11e9-965f-bf3b32117833.png)
![image](https://user-images.githubusercontent.com/17714962/52895912-b1bcbf00-31fb-11e9-9adc-627cbd08f588.png)
![image](https://user-images.githubusercontent.com/17714962/52895914-b97c6380-31fb-11e9-9493-a55749ef8a90.png)

**Comment by sishen** [comment]
@zhujianguo postinstall 的 hook.js 跑了吗，可以尝试把 node_modules 清掉试试看。

**Comment by zhujianguo** [comment]
> @zhujianguo postinstall 的 hook.js 跑了吗，可以尝试把 node_modules 清掉试试看。

有的，通过自动运行脚本和手动运行都试过，你的能成功没这些问题吗？

**Comment by ldkxingzhe** [comment]
根据报错信息显示是RN的Package没有导入成功。 

![12_04_46__02_20_2019](https://user-images.githubusercontent.com/8150898/53065692-c8b72600-3507-11e9-9bad-f1299b74a3ae.jpg)

@zhujianguo 确认下有这一步骤,

**Comment by iShawnWang** [comment]
`import com.growingio.android.plugin.rn.GrowingIOPackage;` 这个好像引用不到了 ? 文档上也没有... 最新的路径是 ? @sishen

**Comment by ldkxingzhe** [comment]
@iShawnWang 这个包名是没有更改的, 出现引用找不到的原因应该是依赖没有找到， 可以参照官网: 
![rn](https://user-images.githubusercontent.com/8150898/58447219-52ddde80-8136-11e9-9120-103c6c12b2a3.jpg)
其中红色窗口替换成RN-autotrack-2.7.5@aar， 并留意是否网络下载失败

**Comment by iShawnWang** [comment]
已解决 感谢 @ldkxingzhe  🎉
