### ISSUE TITLE
SDK初始化:cannot resolve symbol:GrowingIOPackage

### ISSUE THREAD

**Issue by xiaochao** [growingio/react-native-growingio#8]
按照官方教程操作后，报错如题，package.json如下：

{
  "name": "ding",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "postinstall": "node node_modules/react-native-autotrack-growingio/hook.js -run"
  },
  "dependencies": {
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-autotrack-growingio": "0.0.5",
    "react-native-gesture-handler": "^1.2.1",
    "react-navigation": "^3.9.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by ldkxingzhe** [comment]
GrowingIO的RN SDK需要搭配对应平台的Android或IOS SDK， 这个GrowingIOPackage就是一个native模块， 可以参见https://docs.growingio.com/docs/sdk-integration/react-native-wu-mai-dian-sdk/ 官网链接， 也可参见我们的演示demo

**Comment by lizwangying** [comment]
@xiaochao  请使用 Android Studio 集成SDK，应该是你没有集成 Android platform 部分，或者是没有导包？ 可以查看 demo 中的 build.gradle , 和 Application。 请仔细看图中这三个文件中的集成配置。
![image](https://user-images.githubusercontent.com/13509775/58448156-853d0b00-8139-11e9-847c-9a17832f9efd.png)

**Comment by lizwangying** [comment]
https://github.com/growingio/ReactNativeDemo

**Comment by xiaochao** [comment]
![image](https://user-images.githubusercontent.com/1953662/58456803-b6c4cf00-8157-11e9-94c6-6215aa52bb87.png)

GrowingIO SDK已经安装好了，见图，但是没有GrowingIOPackage

**Comment by xiaochao** [comment]
@ldkxingzhe 按照教程操作，一模一样

**Comment by ldkxingzhe** [comment]
@xiaochao 方便提供下配置dependencies的build.gradle截图吗

**Comment by ldkxingzhe** [comment]
implementation 'com.growingio.android:vds-android-agent:RN-autotrack-2.7.5@aar'

**Comment by xiaochao** [comment]
![image](https://user-images.githubusercontent.com/1953662/58468318-eda6df00-816f-11e9-9d36-d2955be2f8fb.png)
![image](https://user-images.githubusercontent.com/1953662/58468339-f7304700-816f-11e9-9c1d-70a22212d5b1.png)
上面是moudle的build.gradle

下面是project的build.gradle
![image](https://user-images.githubusercontent.com/1953662/58468422-19c26000-8170-11e9-89ef-eb3ee3dc7c33.png)

**Comment by ldkxingzhe** [comment]
@xiaochao 所有的autotrack-2.7.5 版本号改成RN-autotrack-2.7.5

**Comment by xiaochao** [comment]
解决了，多谢
