### ISSUE TITLE
yarn命令安装失败

### ISSUE THREAD

**Issue by summer88123** [growingio/react-native-growingio#9]
使用 yarn add https://github.com/growingio/react-native-growingio.git#0.0.7 命令安装时失败。
报错信息：
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://github.com/growingio/react-native-growingio.git /Users/hecom/Library/Caches/Yarn/v4/.tmp/71e0b1ffa25b82539b384ccfc9aaf700
Directory: /Users/hecom/.jenkins/workspace/CRMPlus-Android
Output:
Cloning into '/Users/hecom/Library/Caches/Yarn/v4/.tmp/71e0b1ffa25b82539b384ccfc9aaf700'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

有人遇到过这个情况么？

应该是和大文件有关系，但试了一些网上相关的修改git config的方式，都无效。

临时解决方案：使用git clone命令单独将项目下载下来，手动复制到yarn的缓存目录，可以绕过yarn的下载。

**Comment by NanNanCHN** [comment]
@summer88123 您可以先使用npm install --save https://github.com/growingio/react-native-growingio.git\#0.0.7 速度很快 这个tag里面的内容很小,当然您的解决方式也可以,我估计yarn add 会clone历史版本 历史中包很大 影响的速度,后期 我们会不在更新这个仓库,把这个插件放在native包里面 从而减少集成步骤
